# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  kiwiNet:

services:
  ca.org1.kiwi.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca_peerOrg1
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.kiwi.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/97c8d886efad2167bd529ee1bb6375decea3b0962fe35831d3e4b86343ff79fa_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.kiwi.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/97c8d886efad2167bd529ee1bb6375decea3b0962fe35831d3e4b86343ff79fa_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./channel/crypto-config/peerOrganizations/org1.kiwi.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg1
    networks:
      - kiwiNet

  ca.org2.kiwi.com:
    container_name: ca_peerOrg2
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca_peerOrg2
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.kiwi.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/779e10fa3d122c7a3fb703367ab441d15eb64862685a5d0fe3487c341156ee7e_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.kiwi.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/779e10fa3d122c7a3fb703367ab441d15eb64862685a5d0fe3487c341156ee7e_sk
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./channel/crypto-config/peerOrganizations/org2.kiwi.com/ca/:/etc/hyperledger/fabric-ca-server-config
    ports:
      - "8054:7054"
    networks:
      - kiwiNet

  orderer.kiwi.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.kiwi.com
    container_name: orderer.kiwi.com
    networks:
      - kiwiNet

  peer0.org1.kiwi.com:
    container_name: peer0.org1.kiwi.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org1.kiwi.com
    depends_on:
      - orderer.kiwi.com  
    networks:
      - kiwiNet

  peer1.org1.kiwi.com:
    container_name: peer1.org1.kiwi.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org1.kiwi.com
    depends_on:
      - orderer.kiwi.com
    networks:
      - kiwiNet

  peer0.org2.kiwi.com:
    container_name: peer0.org2.kiwi.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org2.kiwi.com
    depends_on:
      - orderer.kiwi.com
    networks:
      - kiwiNet

  peer1.org2.kiwi.com:
    container_name: peer1.org2.kiwi.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org2.kiwi.com
    depends_on:
      - orderer.kiwi.com
    networks:
      - kiwiNet

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      #- CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.kiwi.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.kiwi.com/peers/peer0.org1.kiwi.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.kiwi.com/peers/peer0.org1.kiwi.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.kiwi.com/peers/peer0.org1.kiwi.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.kiwi.com/users/Admin@org1.kiwi.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        #- ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./channel/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./channel/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.kiwi.com
      - peer0.org1.kiwi.com
      - peer1.org1.kiwi.com
      - peer0.org2.kiwi.com
      - peer1.org2.kiwi.com
    networks:
      - kiwiNet
